import { ModelDefinition } from "@/schema/model";
import { RelationSchema } from "@/types/relation";
import { checkBelongsTo } from "./checkBelongsTo";
import { checkBelongsToSchema } from "./checkBelongsToSchema";
import { checkInverse } from "./checkInverse";
import { checkInverseSchema } from "./checkInverseSchema";
import { formatViolations } from "./format";
import { ValidationResult, RelationViolation } from "./types";

export type { ValidationResult, RelationViolation };
export type { ViolationKind } from "./types";

// ─── validateRelations ────────────────────────────────────────────────────────

/**
 * Validate all relations across a set of models.
 *
 * Runs two independent passes and collects every violation before returning:
 *
 *   Pass 1 (`checkBelongsTo`) — every `belongsTo` must have a matching
 *   `hasMany` or `hasOne` on the target model.
 *
 *   Pass 2 (`checkInverse`) — every `hasMany` / `hasOne` with a `mappedBy`
 *   must have a matching `belongsTo` on the target model.
 *
 * Returns `{ valid: true, violations: [] }` when everything is wired correctly.
 * Returns `{ valid: false, violations: [...] }` with every problem found.
 */
export function validateRelations(models: ModelDefinition[]): ValidationResult {
  const modelMap = new Map<string, ModelDefinition>(
    models.map((m) => [m._tableName, m]),
  );

  const violations: RelationViolation[] = [];

  for (const model of models) {
    violations.push(...checkBelongsTo(model, modelMap));
    violations.push(...checkInverse(model, modelMap));
  }

  return { valid: violations.length === 0, violations };
}

// ─── assertValidRelations ─────────────────────────────────────────────────────

/**
 * Like `validateRelations` but throws a single `RelationValidationError` that
 * lists **all** violations when any are found.
 *
 * Intended for use at module-init time so broken schemas are caught early.
 *
 * ```ts
 * assertValidRelations([UserSchema, OrderSchema, OrderItemSchema]);
 * ```
 *
 * On failure the error message looks like:
 * ```
 * Found 2 relation violation(s):
 *
 *  1. [missing_inverse]
 *       order_item.order is a belongsTo → order
 *       but order has no "order_items" property pointing back.
 *       ...
 *
 *  2. [missing_belongsTo]
 *       ...
 * ```
 */
export function assertValidRelations(models: ModelDefinition[]): void {
  const result = validateRelations(models);
  if (!result.valid) {
    throw new RelationValidationError(result.violations);
  }
}

// ─── validateRelationSchemas ──────────────────────────────────────────────────

/**
 * Validate all relations against the final serialized `RelationSchema[]` array
 * (the `relationships` field of a `ModuleSchema` / snapshot).
 *
 * Unlike `validateRelations` (which inspects live `ModelDefinition` builder
 * objects), this function operates purely on the serialized output — useful for
 * validating a schema that was loaded from JSON, generated by a third-party
 * tool, or produced after `toModuleSchema()` has already run.
 *
 * Runs two independent passes and collects every violation before returning:
 *
 *   Pass 1 (`checkBelongsToSchema`) — every `belongsTo` with a `mappedBy`
 *   must have a matching `hasMany`/`hasOne` pointing back in the array.
 *
 *   Pass 2 (`checkInverseSchema`) — every `hasMany`/`hasOne` with a `mappedBy`
 *   must have a matching `belongsTo` pointing back in the array.
 *
 * Returns `{ valid: true, violations: [] }` when everything is consistent.
 * Returns `{ valid: false, violations: [...] }` with every problem found.
 */
export function validateRelationSchemas(
  relationships: RelationSchema[],
): ValidationResult {
  const violations: RelationViolation[] = [];

  violations.push(...checkBelongsToSchema(relationships));
  violations.push(...checkInverseSchema(relationships));

  return { valid: violations.length === 0, violations };
}

// ─── assertValidRelationSchemas ───────────────────────────────────────────────

/**
 * Like `validateRelationSchemas` but throws a single `RelationValidationError`
 * that lists **all** violations when any are found.
 *
 * Intended for validating a `ModuleSchema` loaded from a snapshot or built
 * externally, without access to the original `ModelDefinition` instances.
 *
 * ```ts
 * assertValidRelationSchemas(moduleSchema.relationships);
 * ```
 */
export function assertValidRelationSchemas(
  relationships: RelationSchema[],
): void {
  const result = validateRelationSchemas(relationships);
  if (!result.valid) {
    throw new RelationValidationError(result.violations);
  }
}

// ─── RelationValidationError ──────────────────────────────────────────────────

/**
 * Thrown by `assertValidRelations` when one or more relation violations are
 * found.  Carries the full list of violations and a formatted message.
 */
export class RelationValidationError extends Error {
  readonly violations: RelationViolation[];

  constructor(violations: RelationViolation[]) {
    super(formatViolations(violations));
    this.name = "RelationValidationError";
    this.violations = violations;
  }
}
