export const jobs001ObservabilitySql = `
CREATE TABLE "_damat_job_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL, "attempt_number" INTEGER,
  "type" TEXT NOT NULL, "previous_status" TEXT, "next_status" TEXT,
  "worker_id" TEXT, "lease_token" UUID,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "reason" TEXT, "duration_ms" BIGINT,
  "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "_damat_job_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_activity_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_job_activity_attempt_fkey"
    FOREIGN KEY ("run_id", "attempt_number")
    REFERENCES "_damat_job_attempts" ("run_id", "attempt_number"),
  CONSTRAINT "_damat_job_activity_duration_ms_check"
    CHECK ("duration_ms" IS NULL OR "duration_ms" >= 0),
  CONSTRAINT "_damat_job_activity_status_check" CHECK (
    ("previous_status" IS NULL OR "previous_status" IN
      ('queued','running','retry_wait','succeeded','dead_lettered','cancelled'))
    AND ("next_status" IS NULL OR "next_status" IN
      ('queued','running','retry_wait','succeeded','dead_lettered','cancelled')))
);
CREATE INDEX "_damat_job_activity_run_idx"
  ON "_damat_job_activity" ("run_id", "id");

CREATE TABLE "_damat_job_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL, "attempt_number" INTEGER NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "level" TEXT NOT NULL,
  "message" TEXT NOT NULL, "context" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "worker_id" TEXT, "correlation_id" TEXT, "trace_id" TEXT,
  "sequence" INTEGER NOT NULL,
  CONSTRAINT "_damat_job_logs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_logs_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_job_logs_attempt_fkey"
    FOREIGN KEY ("run_id", "attempt_number")
    REFERENCES "_damat_job_attempts" ("run_id", "attempt_number"),
  CONSTRAINT "_damat_job_logs_level_check"
    CHECK ("level" IN ('debug','info','warn','error')),
  CONSTRAINT "_damat_job_logs_sequence_check" CHECK ("sequence" > 0),
  CONSTRAINT "_damat_job_logs_sequence_uidx"
    UNIQUE ("run_id", "attempt_number", "sequence")
);
CREATE INDEX "_damat_job_logs_run_idx" ON "_damat_job_logs"
  ("run_id", "attempt_number", "sequence");
`.trim();
