import type { SystemMigration } from "@damatjs/durability";

export const jobs001: SystemMigration = {
  owner: "@damatjs/jobs",
  id: "001",
  order: 300,
  sql: `
CREATE TABLE "_damat_job_runs" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL, "queue" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'queued',
  "payload" JSONB NOT NULL, "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "priority" INTEGER NOT NULL DEFAULT 100,
  "available_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "attempt_count" INTEGER NOT NULL DEFAULT 0,
  "max_attempts" INTEGER NOT NULL DEFAULT 3,
  "backoff_ms" INTEGER NOT NULL DEFAULT 1000,
  "backoff_multiplier" DOUBLE PRECISION NOT NULL DEFAULT 2,
  "lease_owner" TEXT, "lease_token" UUID, "lease_expires_at" TIMESTAMPTZ,
  "heartbeat_at" TIMESTAMPTZ, "cancellation_requested_at" TIMESTAMPTZ,
  "schedule_id" UUID, "scheduled_for" TIMESTAMPTZ,
  "deduplication_key" TEXT, "progress" JSONB, "result" JSONB,
  "correlation_id" TEXT, "last_error" JSONB,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "started_at" TIMESTAMPTZ, "completed_at" TIMESTAMPTZ,
  CONSTRAINT "_damat_job_runs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_runs_status_check" CHECK ("status" IN
    ('queued','running','retry_wait','succeeded','dead_lettered','cancelled')),
  CONSTRAINT "_damat_job_runs_attempt_count_check" CHECK ("attempt_count" >= 0),
  CONSTRAINT "_damat_job_runs_max_attempts_check" CHECK ("max_attempts" > 0),
  CONSTRAINT "_damat_job_runs_backoff_ms_check" CHECK ("backoff_ms" >= 0),
  CONSTRAINT "_damat_job_runs_backoff_multiplier_check"
    CHECK ("backoff_multiplier" >= 1)
);
CREATE INDEX "_damat_job_runs_due_idx" ON "_damat_job_runs"
  ("queue", "status", "available_at", "priority", "created_at");
CREATE INDEX "_damat_job_runs_name_idx" ON "_damat_job_runs"
  ("name", "created_at");

CREATE TABLE "_damat_job_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL, "attempt_number" INTEGER NOT NULL,
  "worker_id" TEXT NOT NULL, "lease_token" UUID NOT NULL,
  "started_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "heartbeat_at" TIMESTAMPTZ, "finished_at" TIMESTAMPTZ,
  "duration_ms" INTEGER, "result" JSONB, "outcome" TEXT, "error" JSONB,
  CONSTRAINT "_damat_job_attempts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_attempts_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_job_attempts_number_uidx"
    UNIQUE ("run_id", "attempt_number"),
  CONSTRAINT "_damat_job_attempts_number_check" CHECK ("attempt_number" > 0),
  CONSTRAINT "_damat_job_attempts_outcome_check" CHECK ("outcome" IS NULL OR
    "outcome" IN ('succeeded','retry_wait','dead_lettered','cancelled','lost'))
);

CREATE TABLE "_damat_job_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL, "attempt_number" INTEGER,
  "type" TEXT NOT NULL, "previous_status" TEXT, "next_status" TEXT,
  "worker_id" TEXT, "lease_token" UUID,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "reason" TEXT, "duration_ms" INTEGER,
  "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "_damat_job_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_activity_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_job_activity_status_check" CHECK (
    ("previous_status" IS NULL OR "previous_status" IN
      ('queued','running','retry_wait','succeeded','dead_lettered','cancelled'))
    AND ("next_status" IS NULL OR "next_status" IN
      ('queued','running','retry_wait','succeeded','dead_lettered','cancelled')))
);
CREATE INDEX "_damat_job_activity_run_idx" ON "_damat_job_activity"
  ("run_id", "occurred_at", "id");

CREATE TABLE "_damat_job_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL, "attempt_number" INTEGER NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "level" TEXT NOT NULL,
  "message" TEXT NOT NULL, "context" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "worker_id" TEXT, "correlation_id" TEXT, "trace_id" TEXT,
  "sequence" INTEGER NOT NULL,
  CONSTRAINT "_damat_job_logs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_logs_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_job_logs_level_check"
    CHECK ("level" IN ('debug','info','warn','error')),
  CONSTRAINT "_damat_job_logs_sequence_check" CHECK ("sequence" > 0),
  CONSTRAINT "_damat_job_logs_sequence_uidx"
    UNIQUE ("run_id", "attempt_number", "sequence")
);
CREATE INDEX "_damat_job_logs_run_idx" ON "_damat_job_logs"
  ("run_id", "attempt_number", "sequence");
`.trim(),
};
