import type { SystemMigration } from "@damatjs/durability";

export const jobs002: SystemMigration = {
  owner: "@damatjs/jobs",
  id: "002",
  order: 400,
  sql: `
CREATE TABLE "_damat_job_schedules" (
  "id" UUID NOT NULL, "name" TEXT NOT NULL, "job_name" TEXT NOT NULL,
  "kind" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "payload" JSONB NOT NULL, "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "queue" TEXT NOT NULL, "priority" INTEGER NOT NULL DEFAULT 100,
  "max_attempts" INTEGER NOT NULL DEFAULT 3,
  "backoff_ms" INTEGER NOT NULL DEFAULT 1000,
  "backoff_multiplier" DOUBLE PRECISION NOT NULL DEFAULT 2,
  "run_at" TIMESTAMPTZ, "interval_ms" INTEGER,
  "next_occurrence_at" TIMESTAMPTZ, "last_occurrence_at" TIMESTAMPTZ,
  "deduplication_key" TEXT, "deduplication_ttl_ms" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_job_schedules_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_schedules_name_uidx" UNIQUE ("name"),
  CONSTRAINT "_damat_job_schedules_kind_check"
    CHECK ("kind" IN ('once','interval','cron')),
  CONSTRAINT "_damat_job_schedules_interval_check"
    CHECK ("interval_ms" IS NULL OR "interval_ms" > 0),
  CONSTRAINT "_damat_job_schedules_max_attempts_check"
    CHECK ("max_attempts" > 0)
);
CREATE INDEX "_damat_job_schedule_due_idx" ON "_damat_job_schedules"
  ("enabled", "next_occurrence_at");

CREATE TABLE "_damat_job_schedule_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "schedule_id" UUID NOT NULL, "type" TEXT NOT NULL,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "_damat_job_schedule_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_job_schedule_activity_schedule_fkey"
    FOREIGN KEY ("schedule_id") REFERENCES "_damat_job_schedules" ("id")
    ON DELETE CASCADE
);
CREATE INDEX "_damat_job_schedule_activity_idx"
  ON "_damat_job_schedule_activity" ("schedule_id", "occurred_at", "id");

CREATE TABLE "_damat_job_deduplication" (
  "queue" TEXT NOT NULL, "job_name" TEXT NOT NULL,
  "deduplication_key" TEXT NOT NULL, "run_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "expires_at" TIMESTAMPTZ,
  CONSTRAINT "_damat_job_deduplication_pkey"
    PRIMARY KEY ("queue", "job_name", "deduplication_key"),
  CONSTRAINT "_damat_job_deduplication_run_fkey" FOREIGN KEY ("run_id")
    REFERENCES "_damat_job_runs" ("id") ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "_damat_job_deduplication_expires_idx"
  ON "_damat_job_deduplication" ("expires_at");

ALTER TABLE "_damat_job_runs"
  ADD CONSTRAINT "_damat_job_runs_schedule_fkey" FOREIGN KEY ("schedule_id")
  REFERENCES "_damat_job_schedules" ("id") ON DELETE SET NULL;
CREATE UNIQUE INDEX "_damat_job_schedule_occurrence_uidx"
  ON "_damat_job_runs" ("schedule_id", "scheduled_for")
  WHERE "schedule_id" IS NOT NULL;
`.trim(),
};
