import { describe, it, expect } from "bun:test";
import {
  toCamel,
  toPascal,
  packageJsonTemplate,
  tsconfigTemplate,
  manifestTemplate,
  moduleConfigTemplate,
  entryTemplate,
  serviceTemplate,
  contractTestTemplate,
  envExampleTemplate,
  gitignoreTemplate,
  readmeTemplate,
  configSchemaTemplate,
  configLoadTemplate,
  configIndexTemplate,
} from "../../commands/module/scaffold/templates";
export {
  describe,
  it,
  expect,
  toCamel,
  toPascal,
  packageJsonTemplate,
  tsconfigTemplate,
  manifestTemplate,
  moduleConfigTemplate,
  entryTemplate,
  serviceTemplate,
  contractTestTemplate,
  envExampleTemplate,
  gitignoreTemplate,
  readmeTemplate,
  configSchemaTemplate,
  configLoadTemplate,
  configIndexTemplate,
};
