export const pipelines001RuntimeSql = `
CREATE TABLE "_damat_pipeline_transitions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID NOT NULL,
  "from_execution_id" UUID,
  "to_execution_id" UUID,
  "edge" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "reason" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_pipeline_transitions_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_pipeline_transitions_edge_key" UNIQUE
    ("run_id","from_execution_id","to_execution_id"),
  CONSTRAINT "_damat_pipeline_transitions_run_fkey" FOREIGN KEY
    ("run_id") REFERENCES "_damat_pipeline_runs"("id") ON DELETE CASCADE
);

CREATE TABLE "_damat_pipeline_signals" (
  "id" UUID NOT NULL,
  "run_id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "payload" JSONB NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "actor" JSONB NOT NULL,
  "reason" TEXT NOT NULL,
  "consumed_by" UUID,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "consumed_at" TIMESTAMPTZ,
  CONSTRAINT "_damat_pipeline_signals_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_pipeline_signals_run_fkey" FOREIGN KEY
    ("run_id") REFERENCES "_damat_pipeline_runs"("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_pipeline_signals_execution_fkey" FOREIGN KEY
    ("consumed_by") REFERENCES "_damat_pipeline_node_executions"("id"),
  CONSTRAINT "_damat_pipeline_signals_idempotency_key"
    UNIQUE ("run_id","name","idempotency_key")
);

CREATE TABLE "_damat_pipeline_trigger_receipts" (
  "id" UUID NOT NULL,
  "version_id" UUID NOT NULL,
  "trigger_id" TEXT NOT NULL,
  "source_id" TEXT NOT NULL,
  "run_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_pipeline_trigger_receipts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_pipeline_trigger_receipts_version_fkey" FOREIGN KEY
    ("version_id") REFERENCES "_damat_pipeline_versions"("id"),
  CONSTRAINT "_damat_pipeline_trigger_receipts_run_fkey" FOREIGN KEY
    ("run_id") REFERENCES "_damat_pipeline_runs"("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_pipeline_trigger_receipts_source_key"
    UNIQUE ("version_id","trigger_id","source_id")
);

CREATE TABLE "_damat_pipeline_schedules" (
  "version_id" UUID NOT NULL,
  "trigger_id" TEXT NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "next_at" TIMESTAMPTZ NOT NULL,
  "last_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_pipeline_schedules_pkey" PRIMARY KEY
    ("version_id","trigger_id"),
  CONSTRAINT "_damat_pipeline_schedules_version_fkey" FOREIGN KEY
    ("version_id") REFERENCES "_damat_pipeline_versions"("id") ON DELETE CASCADE
);

CREATE TABLE "_damat_pipeline_trigger_controls" (
  "version_id" UUID NOT NULL,
  "trigger_id" TEXT NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "reason" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_pipeline_trigger_controls_pkey" PRIMARY KEY
    ("version_id","trigger_id"),
  CONSTRAINT "_damat_pipeline_trigger_controls_version_fkey" FOREIGN KEY
    ("version_id") REFERENCES "_damat_pipeline_versions"("id") ON DELETE CASCADE
);

CREATE TABLE "_damat_pipeline_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "run_id" UUID,
  "node_execution_id" UUID,
  "type" TEXT NOT NULL,
  "details" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_pipeline_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_pipeline_activity_run_fkey" FOREIGN KEY
    ("run_id") REFERENCES "_damat_pipeline_runs"("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_pipeline_activity_node_fkey" FOREIGN KEY
    ("node_execution_id") REFERENCES "_damat_pipeline_node_executions"("id")
    ON DELETE CASCADE
);
`;
