import type { PackageDefinition } from "./types";

export const packageList: PackageDefinition[] = [
  { dir: "packages/framework", group: "Framework & app" },
  { dir: "packages/service", group: "Framework & app" },
  { dir: "packages/module", group: "Framework & app" },
  { dir: "packages/module-generator", group: "Framework & app" },
  { dir: "packages/link", group: "Framework & app" },
  { dir: "packages/workflow-engine", group: "Framework & app" },
  { dir: "packages/orm/main", group: "ORM" },
  { dir: "packages/orm/model", group: "ORM" },
  { dir: "packages/orm/pg", group: "ORM" },
  { dir: "packages/orm/connector", group: "ORM" },
  { dir: "packages/orm/migration", group: "ORM" },
  { dir: "packages/orm/processor", group: "ORM" },
  { dir: "packages/core/schema-codegen", group: "ORM" },
  { dir: "packages/orm/core", group: "ORM" },
  { dir: "packages/orm/type", group: "ORM" },
  { dir: "packages/core/logger", group: "Core" },
  { dir: "packages/core/redis", group: "Core" },
  { dir: "packages/core/events", group: "Core" },
  { dir: "packages/core/jobs", group: "Core" },
  { dir: "packages/provider", group: "Providers" },
  { dir: "provider/auth", group: "Providers" },
  { dir: "provider/payment", group: "Providers" },
  { dir: "provider/subscription", group: "Providers" },
  { dir: "packages/core/env", group: "Core" },
  { dir: "packages/core/types", group: "Core" },
  { dir: "packages/core/cli", group: "Core" },
  { dir: "packages/deps", group: "Core" },
  { dir: "packages/typescript-config", group: "Core" },
  { dir: "packages/cli/damat", group: "CLIs & AI" },
  { dir: "packages/cli/codegen", group: "CLIs & AI" },
  { dir: "packages/orm/cli", group: "CLIs & AI" },
  { dir: "packages/mcp", group: "CLIs & AI" },
];
