import type { LinkDraft } from "./link";

/** Kebab/snake → camelCase, for import identifiers ("user-organization" → "userOrganization"). */
export function camelize(name: string): string {
  return name.replace(/[-_]([a-z0-9])/gi, (_, c: string) => c.toUpperCase());
}

/** A draft is ready to materialize once both endpoints name a module and model. */
export function isReadyDraft(draft: LinkDraft): boolean {
  return Boolean(
    draft.from.module && draft.from.model && draft.to.module && draft.to.model,
  );
}

/** The endpoint fields still blank on a not-ready draft (for a helpful warning). */
export function draftBlanks(draft: LinkDraft): string[] {
  const missing: string[] = [];
  if (!draft.from.module) missing.push("from.module");
  if (!draft.from.model) missing.push("from.model");
  if (!draft.to.module) missing.push("to.module");
  if (!draft.to.model) missing.push("to.model");
  return missing;
}

function renderEndpoint(ep: LinkDraft["from"]): string {
  const parts = [
    `module: ${JSON.stringify(ep.module)}`,
    `model: ${JSON.stringify(ep.model)}`,
  ];
  if (ep.field) parts.push(`field: ${JSON.stringify(ep.field)}`);
  if (ep.primaryKey) parts.push(`primaryKey: ${JSON.stringify(ep.primaryKey)}`);
  if (ep.isList !== undefined) parts.push(`isList: ${ep.isList}`);
  return `{ ${parts.join(", ")} }`;
}

/** The `defineLink(...)` module file for a single ready draft. */
export function renderLinkModel(draft: LinkDraft): string {
  const opts: string[] = [];
  if (draft.pivotTable)
    opts.push(`pivotTable: ${JSON.stringify(draft.pivotTable)}`);
  if (draft.foreignKeys) opts.push(`database: { foreignKeys: true }`);
  const optionsArg = opts.length > 0 ? `\n  { ${opts.join(", ")} },` : "";

  return `import { defineLink } from "@damatjs/framework";

/**
 * Cross-module link generated by \`damat module link-setup\` from a module's
 * declared rule. Neither module imports the other — the relationship lives here
 * under links/${draft.owner} (the owning module). Edit freely; re-running the
 * command will not overwrite this file.
 */
export default defineLink(
  ${renderEndpoint(draft.from)},
  ${renderEndpoint(draft.to)},${optionsArg}
);
`;
}

/** The `index.ts` for one owner directory, listing every model file. */
export function renderOwnerIndex(modelBasenames: string[]): string {
  const imports = modelBasenames
    .map((b) => `import ${camelize(b)} from "./models/${b}";`)
    .join("\n");
  const ids = modelBasenames.map((b) => camelize(b)).join(", ");
  return `import { collectLinkModels } from "@damatjs/framework";
${imports}

export const links = [${ids}];
export const models = collectLinkModels(links);
`;
}

/** The top-level `src/links/index.ts` aggregating every owner's links. */
export function renderAggregator(ownerDirs: string[]): string {
  const imports = ownerDirs
    .map((o) => `import { links as ${camelize(o)}Links } from "./${o}";`)
    .join("\n");
  const spreads = ownerDirs.map((o) => `...${camelize(o)}Links`).join(", ");
  return `import { defineLinkModule } from "@damatjs/framework";
${imports}

export const links = [${spreads}];

export default defineLinkModule(links);
`;
}
