export const events002AttemptsSql = `
CREATE TABLE "_damat_event_delivery_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "delivery_id" UUID NOT NULL, "attempt_number" INTEGER NOT NULL,
  "worker_id" TEXT NOT NULL, "lease_token" UUID NOT NULL,
  "started_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "heartbeat_at" TIMESTAMPTZ, "finished_at" TIMESTAMPTZ,
  "duration_ms" BIGINT, "result" JSONB, "outcome" TEXT, "error" JSONB,
  CONSTRAINT "_damat_event_delivery_attempts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_event_delivery_attempts_delivery_fkey"
    FOREIGN KEY ("delivery_id") REFERENCES "_damat_event_deliveries" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "_damat_event_delivery_attempts_number_uidx"
    UNIQUE ("delivery_id", "attempt_number"),
  CONSTRAINT "_damat_event_delivery_attempts_number_check"
    CHECK ("attempt_number" > 0),
  CONSTRAINT "_damat_event_delivery_attempts_duration_ms_check"
    CHECK ("duration_ms" IS NULL OR "duration_ms" >= 0),
  CONSTRAINT "_damat_event_delivery_attempts_outcome_check"
    CHECK ("outcome" IS NULL OR "outcome" IN
      ('succeeded','retry_wait','dead_lettered','cancelled','lost'))
);
`.trim();
