export const events002ObservabilitySql = `
CREATE TABLE "_damat_event_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "event_id" UUID NOT NULL, "delivery_id" UUID, "attempt_number" INTEGER,
  "consumer" TEXT, "type" TEXT NOT NULL,
  "previous_status" TEXT, "next_status" TEXT,
  "worker_id" TEXT, "lease_token" UUID,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "reason" TEXT, "duration_ms" BIGINT,
  "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "_damat_event_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_event_activity_event_fkey" FOREIGN KEY ("event_id")
    REFERENCES "_damat_event_outbox" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_event_activity_delivery_identity_fkey"
    FOREIGN KEY ("delivery_id", "event_id", "consumer")
    REFERENCES "_damat_event_deliveries" ("id", "event_id", "consumer")
    ON DELETE CASCADE,
  CONSTRAINT "_damat_event_activity_attempt_fkey"
    FOREIGN KEY ("delivery_id", "attempt_number")
    REFERENCES "_damat_event_delivery_attempts"
      ("delivery_id", "attempt_number"),
  CONSTRAINT "_damat_event_activity_duration_ms_check"
    CHECK ("duration_ms" IS NULL OR "duration_ms" >= 0),
  CONSTRAINT "_damat_event_activity_delivery_scope_check" CHECK (
    ("delivery_id" IS NULL AND "consumer" IS NULL AND "attempt_number" IS NULL)
    OR ("delivery_id" IS NOT NULL AND "consumer" IS NOT NULL)),
  CONSTRAINT "_damat_event_activity_status_check" CHECK (
    ("previous_status" IS NULL OR "previous_status" IN
      ('pending','running','retry_wait','succeeded','dead_lettered','cancelled'))
    AND ("next_status" IS NULL OR "next_status" IN
      ('pending','running','retry_wait','succeeded','dead_lettered','cancelled')))
);
CREATE INDEX "_damat_event_activity_event_idx"
  ON "_damat_event_activity" ("event_id", "id");

CREATE TABLE "_damat_event_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "event_id" UUID NOT NULL, "delivery_id" UUID NOT NULL,
  "attempt_number" INTEGER NOT NULL, "consumer" TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "level" TEXT NOT NULL,
  "message" TEXT NOT NULL, "context" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "worker_id" TEXT, "correlation_id" TEXT, "trace_id" TEXT,
  "sequence" INTEGER NOT NULL,
  CONSTRAINT "_damat_event_logs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_event_logs_event_fkey" FOREIGN KEY ("event_id")
    REFERENCES "_damat_event_outbox" ("id") ON DELETE CASCADE,
  CONSTRAINT "_damat_event_logs_delivery_identity_fkey"
    FOREIGN KEY ("delivery_id", "event_id", "consumer")
    REFERENCES "_damat_event_deliveries" ("id", "event_id", "consumer")
    ON DELETE CASCADE,
  CONSTRAINT "_damat_event_logs_attempt_fkey"
    FOREIGN KEY ("delivery_id", "attempt_number")
    REFERENCES "_damat_event_delivery_attempts"
      ("delivery_id", "attempt_number"),
  CONSTRAINT "_damat_event_logs_level_check"
    CHECK ("level" IN ('debug','info','warn','error')),
  CONSTRAINT "_damat_event_logs_sequence_check" CHECK ("sequence" > 0),
  CONSTRAINT "_damat_event_logs_sequence_uidx"
    UNIQUE ("delivery_id", "attempt_number", "sequence")
);
CREATE INDEX "_damat_event_logs_delivery_idx"
  ON "_damat_event_logs" ("delivery_id", "attempt_number", "sequence");
`.trim();
