import type { SystemMigration } from "./types";

export const shared002: SystemMigration = {
  owner: "@damatjs/durability",
  id: "002",
  order: 200,
  sql: `
CREATE TABLE "_damat_work_controls" (
  "work_kind" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "paused" BOOLEAN NOT NULL DEFAULT FALSE,
  "reason" TEXT,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_work_controls_pkey" PRIMARY KEY ("work_kind", "scope")
);

CREATE TABLE "_damat_work_control_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "work_kind" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "reason" TEXT,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_work_control_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_work_control_activity_action_check"
    CHECK ("action" IN ('paused', 'resumed'))
);
CREATE INDEX "_damat_work_control_activity_scope_idx"
  ON "_damat_work_control_activity" ("work_kind", "scope", "created_at");

CREATE TABLE "_damat_maintenance_activity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "operation" TEXT NOT NULL,
  "work_kind" TEXT,
  "scope" TEXT,
  "status" TEXT NOT NULL,
  "actor" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "details" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "completed_at" TIMESTAMPTZ,
  CONSTRAINT "_damat_maintenance_activity_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_maintenance_activity_status_check"
    CHECK ("status" IN ('requested', 'completed', 'failed'))
);
CREATE INDEX "_damat_maintenance_activity_lookup_idx"
  ON "_damat_maintenance_activity" ("work_kind", "scope", "created_at");
`.trim(),
};
