import type { SystemMigration } from "./types";

export const shared003: SystemMigration = {
  owner: "@damatjs/durability",
  id: "003",
  order: 250,
  sql: `
CREATE TABLE "_damat_acceleration_outbox" (
  "id" UUID NOT NULL,
  "revision" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "topic" TEXT NOT NULL,
  "resource_kind" TEXT NOT NULL,
  "resource_id" TEXT,
  "scope" TEXT,
  "payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "available_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "published_at" TIMESTAMPTZ,
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "claim_token" UUID,
  "claim_expires_at" TIMESTAMPTZ,
  "last_error" TEXT,
  CONSTRAINT "_damat_acceleration_outbox_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_acceleration_outbox_revision_key" UNIQUE ("revision"),
  CONSTRAINT "_damat_acceleration_outbox_attempts_check" CHECK ("attempts" >= 0)
);
CREATE INDEX "_damat_acceleration_outbox_pending_idx"
  ON "_damat_acceleration_outbox" ("available_at", "revision")
  WHERE "published_at" IS NULL;

CREATE TABLE "_damat_acceleration_state" (
  "id" BOOLEAN NOT NULL DEFAULT TRUE,
  "mode" TEXT NOT NULL DEFAULT 'disabled',
  "last_success_at" TIMESTAMPTZ,
  "projection_checkpoint" BIGINT,
  "last_rebuild_at" TIMESTAMPTZ,
  "fallback_interval_ms" INTEGER NOT NULL DEFAULT 5000,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_acceleration_state_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "_damat_acceleration_state_singleton" CHECK ("id"),
  CONSTRAINT "_damat_acceleration_state_mode_check"
    CHECK ("mode" IN ('healthy', 'degraded', 'disabled'))
);
INSERT INTO "_damat_acceleration_state" ("id") VALUES (TRUE);

CREATE TABLE "_damat_retention_overrides" (
  "work_kind" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "retention_ms" BIGINT,
  "actor" JSONB NOT NULL,
  "reason" TEXT NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "_damat_retention_overrides_pkey" PRIMARY KEY ("work_kind", "scope"),
  CONSTRAINT "_damat_retention_overrides_kind_check"
    CHECK ("work_kind" IN ('job', 'event')),
  CONSTRAINT "_damat_retention_overrides_ms_check"
    CHECK ("retention_ms" IS NULL OR "retention_ms" >= 0)
);
`.trim(),
};
